// <auto-generated />
using AgencjaNieruchomosci.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgencjaNieruchomosci.Migrations.ContextKontoMigrations
{
    [DbContext(typeof(ContextKonto))]
    partial class ContextKontoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AgencjaNieruchomosci.Models.Konto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RolaID");

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("AgencjaNieruchomosci.Models.Rola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pozwolenia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AgencjaNieruchomosci.Models.Konto", b =>
                {
                    b.HasOne("AgencjaNieruchomosci.Models.Rola", "Rola")
                        .WithMany()
                        .HasForeignKey("RolaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rola");
                });
#pragma warning restore 612, 618
        }
    }
}
